FloatLayout:
	Image:
        source: 'sprites/title.png'
        pos_hint: {'y': .25}
    Button:
        text: 'Jouer'
        size_hint: (.2, .1)
        pos_hint: {'x': .4, 'y': .275}
    Button:
        text: 'Option'
        size_hint: (.2, .1)
        pos_hint: {'x': .4, 'y': .150}
    Button:
        text: 'Quitter'
        size_hint: (.2, .1)
        pos_hint: {'x': .4, 'y': .025}
        
